name: come_chat_mobile
version: 1.0.0

environment:
  sdk: '^3.9.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_markdown: ^0.6.18
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf